drop table if exists spittle;
drop table if exists spitter;

create table spitter (
  id integer generated by default as identity (start with 1) not null,
  username varchar(25) not null,
  password varchar(25) not null,
  fullName varchar(100) not null,
  email varchar(50) not null,
  updateByEmail boolean not null,
  CONSTRAINT IDX_spitter_ID PRIMARY KEY (id)
);

create table spittle (
  id integer generated by default as identity (start with 1) not null,
  spitter integer not null,
  message varchar(2000) not null,
  postedTime datetime not null,
  foreign key (spitter) references spitter(id),
  CONSTRAINT IDX_spittle_ID PRIMARY KEY (id)
);
